module.exports = {
	ACCOUNT : 'ACCOUNT',
	ACCOUNTED : 'ACCOUNTED',
	GOT_ACCOUNT : 'GOT_ACCOUNT',

	GOT_CURRENT_USER : 'GOT_CURRENT_USER',
	GOT_USER : 'GOT_USER',

	FOLLOW : 'FOLLOW',
	FOLLOWED : 'FOLLOWED',

	UNFOLLOW : 'UNFOLLOW',
	UNFOLLOWED : 'UNFOLLOWED'
}